
#include "../../LIB/BIT_MATH.h"
#include "../../LIB/STD_TYPES.h"
#include "SPI_conf.h"
#include "SPI_init.h"
#include "SPI_praivat.h"


void SPI_INIT()
{
	//SELECT LSB MSB
#if WRITE_MODE==LSB
	SET_BIT(SPCR,DORD);
#elif WRITE_MODE==MSB
	CLEAR_BIT(SPCR,DORD);
#endif
	//SELECT MASTER
#if SPI_MODE==	MASTER
	SET_BIT(SPCR,MSTR);
	//SELECT CLOCK POLARITY
#if CLOCK_POLATITY_MODE == RAISING
	CLEAR_BIT(SPCR,CPOL);
#elif  CLOCK_POLATITY_MODE == FALLING
	SET_BIT(SPCR,CPOL);
#endif
	//SELECT CLOCK PHASE
#if CLOCK_PHASE_MODE == SAMPLE
	CLEAR_BIT(SPCR,CPHA);
#elif  CLOCK_PHASE_MODE == SETUP
	SET_BIT(SPCR,CPHA);
#endif
	//SELECT D2S
	//SELECT CLOCK
	SET_BIT(SPCR,SPR0);
	CLEAR_BIT(SPCR,SPR1);
	CLEAR_BIT(SPSR,SPI2X);
#elif SPI_MODE== SLAVE
	CLEAR_BIT(SPCR,MSTR);
	SET_BIT(SPCR,SPR0);
		CLEAR_BIT(SPCR,SPR1);
		CLEAR_BIT(SPSR,SPI2X);
#endif
		//ENABLE SPI
	SET_BIT(SPCR,SPE);
}


 void SPI_TRAS_RECIVE( u8 DATA ,u8 *recive )
{
// WRITE COLLISION
	 if(recive !=NULLPTR)
	 {
// SPDR= DATA

	SPDR=DATA;
//BUST WAIT FLAG
	while(GET_BIT(SPSR,SPIF)==0)
//RETURN SPDR
		*recive=  SPDR;
	 }
}
